version: '3'

env:
  OS_TYPE:
    sh: grep '^ID=' /etc/os-release | cut -c 4-99

tasks:

  install:
    desc: install/update neovim
    silent: true
    aliases:
    - "update"
    cmds:
    - task: install-{{.OS_TYPE}}

  install-debian:
    internal: true
    silent: true
    cmds:
    - sudo apt update
    - sudo apt install curl git ripgrep unzip
    - curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    - sudo rm -rf /opt/nvim-linux-x86_64
    - sudo mkdir -p /opt/nvim-linux-x86_64
    - sudo chmod a+rX /opt/nvim-linux-x86_64
    - sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
    - sudo ln -sf /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin/
    - rm nvim-linux-x86_64.tar.gz

  install-nixos:
    internal: true
    silent: true
    cmds:
    - echo "nixos is managed by a config. not doing anything"

